config/routes.rb
Rails.application.routes.draw do
  root 'checks#index'
  post 'checks_new' => 'checks#new'
  post 'checks_show' => 'checks#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  def index

  end

  def new

    agent = Mechanize.new
    page = agent.get("https://transit.yahoo.co.jp/")
    yahoo_form = page.form('search')
    yahoo_form.from = params[:fromstation]
    yahoo_form.to = params[:tostation]
    yahoo_form.s = '1'
    page = agent.submit(yahoo_form, yahoo_form.buttons.first)
    @kekka = []
    elements = page.at('.fare .mark')
    kekka = elements.inner_text
    @kekka << kekka.delete("円")
    @kekka << page.uri
    respond_to do |format|
      format.html
      format.json {render json: @kekka}
    end
  end

  def create
  end

  def delete
  end

  def show

    file = params[:file]
    @csv_data = CSV.read(file.path)
    respond_to do |format|
      format.html
      format.json {render json: @csv_data}
    end

  end

  def edit
  end

  def update
  end

     private
  def checks_params
    params.permit(:fromstation, :tostation,:cost)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/index.html.erb
<h1 class="title">Train Cost Checker</h1>

<Div class="menu">
  <%= form_tag(checks_show_path, method: :post, class: "fileimport",multipart: true) do %>
    <%= file_field_tag :file %>
    <%= submit_tag "ファイルインポート",id:"importbutton" %>
  <% end %>
  <div class="left">
    <Div class="menu__left">
      Input
      <button type="button" id="btn_id">CHECK START</button>
    </Div>

    <% num=0 %>
    <% while num<3 do %>
    <Div class="menu__left" data-no="<%= num %>">
      <%= form_tag(checks_new_path, method: :post, class: "checkform",id:"form#{num}") do %>
        <input placeholder="出発駅" type="text" name="fromstation" class="fromstation">
        <input placeholder="到着駅" type="text" name="tostation" class="tostation">
         <input placeholder="金額" type="text" name="cost" class="cost">
         <input type="submit" value="CHECK" style="display:none;">
      <% end %>
    </Div>
    <% num=num+1 %>
    <% end %>

    </div>
  <div class="right">

  <Div class="menu__right">
    Output
    <button type="button" id="btn_id2" style="display:none;">CSVでエクスポート</button>
    <a style="display:none;" id="downloader" href="#"></a>
  </Div>

</Div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traincostkensaku</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>